In [1]:
import numpy as np

In [4]:
np.random.poisson(size = 10, lam=300)

array([289, 296, 301, 296, 308, 309, 298, 318, 335, 295])

In [5]:
np.random.poisson(size = 10, lam=300)

array([313, 278, 310, 309, 273, 303, 322, 301, 287, 269])

In [6]:
np.random.poisson(size = 10, lam=300)

array([291, 296, 277, 294, 276, 318, 319, 298, 296, 332])

In [7]:
np.random.poisson(size = 10, lam=300)

array([308, 309, 314, 309, 315, 298, 301, 307, 286, 317])